{
 "title": "Kubeshark",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "Bucket",
    "label": "Bucket",
    "query": "buckets()\n  |> filter(fn: (r) => r.name !~ /^_/)\n  |> rename(columns: {name: \"_value\"})\n  |> keep(columns: [\"_value\"])\n"
   },
   {
    "name": "Measurement",
    "label": "Measurement",
    "query": "import \"influxdata/influxdb/schema\"\n\nschema.measurements(bucket: ${Bucket:doublequote})"
   },
   {
    "name": "Namespace",
    "label": "Namespace",
    "query": "import \"influxdata/influxdb/schema\"\nschema.tagValues(bucket: ${Bucket:doublequote}, tag: \"namespace\")"
   },
   {
    "name": "DstName",
    "label": "Destination Name",
    "query": "from(bucket: ${Bucket:doublequote})\n  |> range(start: v.timeRangeStart)\n  |> filter(fn: (r) => r[\"_measurement\"] == ${Measurement:doublequote})\n  |> filter(fn: (r) => contains(value: r[\"namespace\"], set: ${Namespace:json}))\n  |> keyValues(keyColumns: [\"dst_name\", \"_field\"])\n  |> group()\n  |> keep(columns: [\"dst_name\"])\n  |> distinct(column: \"dst_name\")\n"
   },
   {
    "name": "DstIP",
    "label": "Destination IP",
    "query": "from(bucket: ${Bucket:doublequote})\n  |> range(start: v.timeRangeStart)\n  |> filter(fn: (r) => r[\"_measurement\"] == ${Measurement:doublequote})\n  |> filter(fn: (r) => contains(value: r[\"namespace\"], set: ${Namespace:json}))\n  |> filter(fn: (r) => contains(value: r[\"dst_name\"], set: ${DstName:json}))\n  |> keyValues(keyColumns: [\"dst_ip\", \"_field\"])\n  |> group()\n  |> keep(columns: [\"dst_ip\"])\n  |> distinct(column: \"dst_ip\")\n"
   },
   {
    "name": "SrcName",
    "label": "Source Name",
    "query": "from(bucket: ${Bucket:doublequote})\n  |> range(start: v.timeRangeStart)\n  |> filter(fn: (r) => r[\"_measurement\"] == ${Measurement:doublequote})\n  |> filter(fn: (r) => contains(value: r[\"namespace\"], set: ${Namespace:json}))\n  |> filter(fn: (r) => contains(value: r[\"dst_name\"], set: ${DstName:json}))\n  |> keyValues(keyColumns: [\"src_name\", \"_field\"])\n  |> group()\n  |> keep(columns: [\"src_name\"])\n  |> distinct(column: \"src_name\")\n"
   },
   {
    "name": "SrcIP",
    "label": "Source IP",
    "query": "from(bucket: ${Bucket:doublequote})\n  |> range(start: v.timeRangeStart)\n  |> filter(fn: (r) => r[\"_measurement\"] == ${Measurement:doublequote})\n  |> filter(fn: (r) => contains(value: r[\"namespace\"], set: ${Namespace:json}))\n  |> filter(fn: (r) => contains(value: r[\"src_name\"], set: ${DstName:json}))\n  |> keyValues(keyColumns: [\"src_ip\", \"_field\"])\n  |> group()\n  |> keep(columns: [\"src_ip\"])\n  |> distinct(column: \"src_ip\")\n"
   },
   {
    "name": "Path",
    "label": "Path",
    "query": "from(bucket: ${Bucket:doublequote})\n  |> range(start: v.timeRangeStart)\n  |> filter(fn: (r) => r[\"_measurement\"] == ${Measurement:doublequote})\n  |> filter(fn: (r) => contains(value: r[\"dst_name\"], set: ${DstName:json}))\n  |> filter(fn: (r) => contains(value: r[\"src_name\"], set: ${SrcName:json}))\n  |> filter(fn: (r) => contains(value: r[\"dst_ip\"], set: ${DstIP:json}))\n  |> filter(fn: (r) => contains(value: r[\"src_ip\"], set: ${SrcIP:json}))\n  |> keyValues(keyColumns: [\"path\", \"_field\"])\n  |> group()\n  |> keep(columns: [\"path\"])\n  |> distinct(column: \"path\")"
   },
   { "name": "AggPer", "label": "Aggregation Period", "query": "1m, 1h, 1d, 1w" }
  ]
 },
 "panels": [
  {
   "title": "Aggregated Latency per Time Period",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "from(bucket: ${Bucket:doublequote})\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == ${Measurement:doublequote})\n  |> filter(fn: (r) => r[\"_field\"] == \"latency\")\n  |> filter(fn: (r) => contains(value: r[\"namespace\"], set: ${Namespace:json}))\n  |> filter(fn: (r) => contains(value: r[\"dst_name\"], set: ${DstName:json}))\n  |> filter(fn: (r) => contains(value: r[\"src_name\"], set: ${SrcName:json}))\n  |> filter(fn: (r) => contains(value: r[\"dst_ip\"], set: ${DstIP:json}))\n  |> filter(fn: (r) => contains(value: r[\"src_ip\"], set: ${SrcIP:json}))\n  |> filter(fn: (r) => contains(value: r[\"path\"], set: ${Path:json}))\n  |> aggregateWindow(every: ${AggPer}, fn: sum, createEmpty: false)\n  |> yield(name: \"aggregated latency\")\n"
    }
   ]
  },
  {
   "title": "Aggregated Bandwidth per Time Period",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "query": "from(bucket: ${Bucket:doublequote})\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == ${Measurement:doublequote})\n  |> filter(fn: (r) => r[\"_field\"] == \"bandwidth\")\n  |> filter(fn: (r) => contains(value: r[\"namespace\"], set: ${Namespace:json}))\n  |> filter(fn: (r) => contains(value: r[\"dst_name\"], set: ${DstName:json}))\n  |> filter(fn: (r) => contains(value: r[\"src_name\"], set: ${SrcName:json}))\n  |> filter(fn: (r) => contains(value: r[\"dst_ip\"], set: ${DstIP:json}))\n  |> filter(fn: (r) => contains(value: r[\"src_ip\"], set: ${SrcIP:json}))\n  |> filter(fn: (r) => contains(value: r[\"path\"], set: ${Path:json}))\n  |> aggregateWindow(every: ${AggPer}, fn: sum, createEmpty: false)\n  |> yield(name: \"aggregated bandwidth\")\n"
    }
   ]
  },
  {
   "title": "API Call Latency Over Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "query": "from(bucket: ${Bucket:doublequote})\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == ${Measurement:doublequote})\n  |> filter(fn: (r) => r[\"_field\"] == \"latency\")\n  |> filter(fn: (r) => contains(value: r[\"namespace\"], set: ${Namespace:json}))\n  |> filter(fn: (r) => contains(value: r[\"dst_name\"], set: ${DstName:json}))\n  |> filter(fn: (r) => contains(value: r[\"src_name\"], set: ${SrcName:json}))\n  |> filter(fn: (r) => contains(value: r[\"dst_ip\"], set: ${DstIP:json}))\n  |> filter(fn: (r) => contains(value: r[\"src_ip\"], set: ${SrcIP:json}))\n  |> filter(fn: (r) => contains(value: r[\"path\"], set: ${Path:json}))\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"latency\")\n\n\n\n\n  "
    }
   ]
  },
  {
   "title": "API Call Status Codes Over Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "targets": [
    {
     "query": "from(bucket: ${Bucket:doublequote})\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == ${Measurement:doublequote})\n  |> filter(fn: (r) => r[\"_field\"] == \"status\")\n  |> filter(fn: (r) => contains(value: r[\"namespace\"], set: ${Namespace:json}))\n  |> filter(fn: (r) => contains(value: r[\"dst_name\"], set: ${DstName:json}))\n  |> filter(fn: (r) => contains(value: r[\"src_name\"], set: ${SrcName:json}))\n  |> filter(fn: (r) => contains(value: r[\"dst_ip\"], set: ${DstIP:json}))\n  |> filter(fn: (r) => contains(value: r[\"src_ip\"], set: ${SrcIP:json}))\n  |> filter(fn: (r) => contains(value: r[\"path\"], set: ${Path:json}))\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"code\")\n\n\n\n\n  "
    }
   ]
  }
 ]
}