{
 "title": "Kubeshark Dashboard V1.0.003",
 "time": { "from": "2024-01-23T20:09:36.000Z", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Kubeshark Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Packets",
   "type": "table",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 1 },
   "repeat": "metric",
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(node) (kubeshark_received_packets_total * on(pod) group_left kube_pod_status_phase{phase=\"Running\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(node) (kubeshark_dropped_packets_total * on(pod) group_left kube_pod_status_phase{phase=\"Running\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(node) (kubeshark_processed_bytes_total * on(pod) group_left kube_pod_status_phase{phase=\"Running\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(node) (kubeshark_dns_packets_total * on(pod) group_left kube_pod_status_phase{phase=\"Running\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(node) (kubeshark_tcp_packets_total * on(pod) group_left kube_pod_status_phase{phase=\"Running\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(node) (kubeshark_icmp_packets_total * on(pod) group_left kube_pod_status_phase{phase=\"Running\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(node) (kubeshark_reassembled_tcp_payloads_total * on(pod) group_left kube_pod_status_phase{phase=\"Running\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(node) (kubeshark_matched_pairs_total * on(pod) group_left kube_pod_status_phase{phase=\"Running\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(node) (kubeshark_dropped_tcp_streams_total * on(pod) group_left kube_pod_status_phase{phase=\"Running\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(node) (kubeshark_live_tcp_streams * on(pod) group_left kube_pod_status_phase{phase=\"Running\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of Packets Received",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "sum by(node) (rate(kubeshark_received_packets_total[$__rate_interval]) * on(pod) group_left(node) kube_pod_info)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Processed Bytes Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by(node) (rate(kubeshark_processed_bytes_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of Packets Dropped",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(node) (rate(kubeshark_dropped_packets_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Dropped Packets Ratio",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by(node) ((rate(kubeshark_dropped_packets_total[$__rate_interval]))/(rate(kubeshark_received_packets_total[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Dropped TCP Streams Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(node) (rate(kubeshark_dropped_tcp_streams_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Workers KPIs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Workers' CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{pod=~\"kubeshark-worker.*\"}) by (node)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Workers' Memory Usage (w/o cache)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", container!=\"\", image!=\"\", pod=~\"kubeshark-worker.*\"}) by (node)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Workers Throughput(Read+Write)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(node) (rate(container_fs_reads_bytes_total{container!=\"\", device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|md.+|dasd.+)\", pod=~\"kubeshark-worker.*\" }[$__rate_interval]) + rate(container_fs_writes_bytes_total{container!=\"\", device=~\"(/dev/)?(mmcblk.p.+|nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|md.+|dasd.+)\", pod=~\"kubeshark-worker.*\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Sniffer CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{pod=~\"kubeshark-worker.*\", container=~\"sniffer\"}) by (container, node)",
     "legendFormat": "{{node}}"
    },
    {
     "expr": "max(\n    kube_pod_container_resource_limits{job=\"kube-state-metrics\",  pod=~\"kubeshark-worker.*\", container=~\"sniffer\", resource=\"cpu\"}\n)",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "Sniffer Memory Usage (w/o cache)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", container!=\"\", image!=\"\", pod=~\"kubeshark-worker.*\", container=~\"sniffer\"}) by (node)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "max(\n    kube_pod_container_resource_limits{job=\"kube-state-metrics\", pod=~\"kubeshark-worker.*\", container=~\"sniffer\", resource=\"memory\"}\n)\n",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "Workers' Received Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{pod=~\"kubeshark-worker.*\"}[$__rate_interval])) by (node)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Tracer CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{pod=~\"kubeshark-worker.*\", container=~\"tracer\"}) by (container, node)",
     "legendFormat": "{{node}}"
    },
    {
     "expr": "max(\n    kube_pod_container_resource_limits{job=\"kube-state-metrics\",  pod=~\"kubeshark-worker.*\", container=~\"tracer\", resource=\"cpu\"}\n)",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "Tracer Memory Usage (w/o cache)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", pod=~\"kubeshark-worker.*\", container=~\"tracer\"}) by (node)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "max(kube_pod_container_resource_limits{job=\"kube-state-metrics\", pod=~\"kubeshark-worker.*\", container=~\"tracer\", resource=\"memory\"})\n",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "Workers' Transmit Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{pod=~\"kubeshark-worker.*\"}[$__rate_interval])) by (node)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Hub & Front KPIs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "Hub & Front' CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{pod=~\"kubeshark-[hub|front].*\"}) by (pod, node)",
     "legendFormat": "{{pod}} --- (Running on: {{node}})"
    }
   ]
  },
  {
   "title": "Hub & Front's Memory Usage (w/o cache)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", container!=\"\", image!=\"\", pod=~\"kubeshark-[front|hub].*\"}) by (pod, node)",
     "legendFormat": "{{pod}} --- (Running on: {{node}})"
    }
   ]
  },
  {
   "title": "Hub & Front' Receive Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{pod=~\"kubeshark-[hub|front].*\"}[$__rate_interval])) by (pod, node)",
     "legendFormat": "{{pod}} --- (Running on: {{node}})"
    }
   ]
  },
  {
   "title": "Hub & Front' Transmit Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{pod=~\"kubeshark-[hub|front].*\"}[$__rate_interval])) by (pod, node)",
     "legendFormat": "{{pod}} --- (Running on: {{node}})"
    }
   ]
  }
 ]
}